"""模型 profile repository 协议。"""

from __future__ import annotations

from typing import Protocol

from cloud_edge_robot_arm.model_control.downloads import ModelDownloadJob
from cloud_edge_robot_arm.model_control.models import ModelProviderProfile


class PlannerProfileRepository(Protocol):
    """只保存非敏感 profile 数据和 active profile id。"""

    def create_profile(self, profile: ModelProviderProfile) -> ModelProviderProfile: ...

    def update_profile(self, profile: ModelProviderProfile) -> ModelProviderProfile: ...

    def get_profile(self, profile_id: str) -> ModelProviderProfile: ...

    def list_profiles(self) -> list[ModelProviderProfile]: ...

    def delete_profile(self, profile_id: str) -> None: ...

    def get_active_profile_id(self) -> str: ...

    def set_active_profile_id(self, profile_id: str) -> None: ...

    def save_download_job(self, job: ModelDownloadJob) -> ModelDownloadJob: ...

    def get_download_job(self, download_id: str) -> ModelDownloadJob: ...

    def list_download_jobs(self) -> list[ModelDownloadJob]: ...
