from __future__ import annotations

ASYNC_RUNTIME = "asyncio"
DETERMINISTIC_TEST_ADAPTER = "MockRobotAdapter"
PHYSICS_SIMULATOR = "MuJoCo"
MODEL_INTEGRATION_ENABLED = False
REAL_ROBOT_INTEGRATION_ENABLED = False
MQTT_INTEGRATION_ENABLED = False
