bigsmall_interfaces/CommandHeader header
geometry_msgs/PoseStamped target_pose
float64 timeout_s
float64 position_tolerance_m
float64 orientation_tolerance_rad
---
bool success
string status
float64 final_sim_time_s
float64 tcp_position_error_m
float64 tcp_orientation_error_rad
---
float64 sim_time_s
float64 ros_time_s
float64 completion_ratio
bool stale_feedback
