"""安全错误构造工具。

统一生成安全相关 StructuredError，保证拒绝、暂停和急停原因可审计。
"""

from __future__ import annotations

from cloud_edge_robot_arm.errors import StructuredError


def safety_error(
    code: str,
    message: str,
    *,
    details: dict[str, object] | None = None,
) -> StructuredError:
    return StructuredError(
        code=code,
        message=message,
        category="SAFETY_SHIELD",
        details=dict(details or {}),
    )


STOP_FAILED = "SAFETY_STOP_FAILED"
WATCHDOG_TIMEOUT = "WATCHDOG_TIMEOUT"
TASK_DEADLINE_EXCEEDED = "TASK_DEADLINE_EXCEEDED"
COMMAND_EXPIRED = "COMMAND_EXPIRED"
SCENE_FRESHNESS_STALE = "SCENE_FRESHNESS_STALE"
SCENE_VERSION_MISMATCH = "SCENE_VERSION_MISMATCH"
CONTEXT_MISMATCH = "CONTEXT_MISMATCH"
DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"
ESTOP_ACTIVE = "ESTOP_ACTIVE"
COLLISION_DETECTED = "COLLISION_DETECTED"
WORKSPACE_VIOLATION = "WORKSPACE_VIOLATION"
FORBIDDEN_ZONE_VIOLATION = "FORBIDDEN_ZONE_VIOLATION"
REACHABILITY_VIOLATION = "REACHABILITY_VIOLATION"
VELOCITY_EXCEEDED = "VELOCITY_EXCEEDED"
JOINT_VELOCITY_EXCEEDED = "JOINT_VELOCITY_EXCEEDED"
ACCELERATION_EXCEEDED = "ACCELERATION_EXCEEDED"
MINIMUM_HEIGHT_VIOLATION = "MINIMUM_HEIGHT_VIOLATION"
OBSTACLE_DISTANCE_VIOLATION = "OBSTACLE_DISTANCE_VIOLATION"
PATH_COLLISION = "PATH_COLLISION"
CARRY_SAFETY_MARGIN = "CARRY_SAFETY_MARGIN"
STEP_TIMEOUT = "STEP_TIMEOUT"
SAFETY_BYPASS_REJECTED = "SAFETY_BYPASS_REJECTED"
